Character Attributes and Stats
=============================

== ATTRIBUTES

*Might*

Might is the primary attribute influencing physical attack power. Warriors and other melee classes will want to focus on improving might above all else.

Might influences physical attack scores in three specific ways:

1. There are prerequisite might scores for some weapons, particularly high DMG weapons:
	Ultra Greatsword: MGT 16 // Greatsword: MGT 14 // Greatbow: MGT 14
	Gauntlet: MGT 12 // Sword: MGT 10 // Powered Weapon: MGT 12

2. Might score determines which attack die you use:
	MGT 0 – 4: d2 // MGT 5 – 8: d4 // MGT 9 – 10: d6 // MGT 11 – 12: d8
	MGT 13 – 14: d10 // MGT 15 – 16: d12 // MGT 17 – 18: 1d6+1d8
	MGT 19 – 20: 2d8 // MGT 21 – 22:  3d6 // MGT 23+: d20

3. Weapons that scale with might will do more damage with a higher might score.
	Example: Weapon has MGT scaling of 2 and your character's MGT = 14
	Scaling Mod = (2x14)/10 = 2.4 (Roll percent die for round up chance)

Might also reduces weight penalties from carrying a lot of gear. This enables you to maintain decent evade and hit stats even while fully armored. 

Finally, might also impacts your physical defense score along with constituion. See the Constitution section for details.

*Dexterity*

Dexterity is a key attribute for rogues and archers. It influences character  movement range, evade, and hit stats. Several weapon's also scale with dexterity. 

As with might above, a few weapons have dexterity score prerequisites:
Spear: DEX 10 // Bow: DEX 12 // Longbow: DEX 14 // Greatbow: DEX 14
Reaper: DEX 14 // Cannon: DEX 12 // Dagger: DEX 8

Dexterity scores add to a character's evade, melee and ranged hit score as follows:
	DEX 0-5: -1 // DEX 6-10: 0 // DEX 11-13: +1 // DEX 14-16: +2
	DEX 17-19: +3 // DEX 20-22: +4 // DEX 23-25: +5 // DEX>25: +6

Dexterity also influences agility and movement scores.

*Constitution*

Constitution is a straightforward attribute that influences exactly three things: HP, Physical Defense, and Resistance. It has the most influence on the first and last of those three. A character's initial HP and their HP growth progression are determined by CON scores. Resistance is a simple function of CON and is used for checks against attacks that inflict some sort of negative status. Physical defense (unarmored damage check die) is based on the total of CON and MGT.

1. By default characters have 10 HP. CON adds to this total as follows:
	0-9: +1 per level // 10-14: +2 per level // 15-19: +3 per level // 20-24: +4 per level
	25+: +5 per level 

2. Resistance is determined solely by CON and progresses as follows:
	0-5: +1 per level // 6-25: +1 every 2 levels 

3. Physical Defense is derived from the total value of MGT and CON:
	0 – 9: 1d4 // 10 – 19: 1d6 // 20 – 29: 1d8 // 30 – 39: 1d12 // 40 – 49: 3d6 // 50: 1d20

When fighting naked (armor destroyed or intentionally) you rely solely on your defense roll to reduce damage. If your roll is less than that of the total attack damage, you take full damage to HP. If your roll is equal or greater, you take half damage. If your roll is double or more than the attack damage, then you take zero damage to HP.

**NOTE: There is a skill that allows successful defense rolls to result in zero HP loss.
**NOTE: There are multiple ways to boost your DEF roll.

*Intelligence*

Intelligence is a key attribute for craftsmen and mages. It influences the potency of chemistry techniques as well as spell casting success rate. Neither magic nor craft classes 
can do their jobs particularly well without intelligence.

Specific numbers for how intelligence influences stats are currently only in the attMappings module. Exact formulae will be posted here after more testing work is done.

*Divine*

Divine is another simple attribute that only influences two things: magic attack power, and magic defense. The latter stat is also used for determining elemental resistance.
Like MGT, DIV stat determines both which spells you can learn, and which dice you roll when casting a spell. For all spells that influence HP (healing and attack spells) the
 total power is simply roll + spell base damage. Each spell as a unique base damage score.

Divine score determines which die you use when casting a spell as follows:
	DIV 0 – 4: d2 // DIV 5 – 8: d4 // MGT 9 – 10: d6 // DIV 11 – 12: d8
	DIV 13 – 14: d10 // DIV 15 – 16: d12 // DIV 17 – 18: 1d6+1d8
	DIV 19 – 20: 2d8 // DIV 21 – 22:  3d6 // DIV 23+: d20

Divine score determines Magic Defense roll in the same way as above.

*Artistry*

Artistry is a curious attribute, helpeful to all classes for varying reasons. It influences several stats. For one, melee HIT chance and evade both get modifiers from having 
sufficient artistry. This is useful for Might and Finesse characters. Artistry also influence craft and casting speed, which is useful for craftsmen and mages respectively. 
Finally, artistry adds a modifier to improve success chance and efficacy of all skills, as well as critical hit chance.

Specific numbers for how aritstry influences stats are currently only in the attMappings module. Exact formulae will be posted here after more testing work is done.
