What is Otrera?
===============

== High Level

Otrera is an RPG engine. It is not one specific role-playing game, but rather a system one can
use to make any number of games.

The first iteration of Otrera is simply the rules engine, content creator tool, and game
publisher. Version 1.5 will include analytics modules to gauge how balanced a given game is.
Version 2.0, the "final" version, will include a simple way to customize the engine, including
adding and removing attributes or stats, and changing how stats and combat scores are computed.

I would like to make Otrera work for computer games too. That will be a whole other project
that may start later this year.

== What makes Otrera a good system to use for my RPG?

Otrera is both simple and complex. It allows for rich, deep combat systems that can be fully
managed with a few pieces of paper and some dice rolls. The game publishing module will give
you everything you need to start your adventure immediately, which means more time having
fun and exploring and less time tweaking stat calculations and balancing attributes.

== What are some interesting features of Otrera's combat engine?

Otrera was inspired by a range of stories and games, from Cyberpunk 2020 to Dark Souls.
Some interesting points about the engine are as follows:

1. Stats are determined by six core attributes (like D&D). They are: Might, Constitution,
Dexterity, Artistry, Divine, and Intelligence.

2. Character classes can influence attribute growth, skill acquisition, both, or neither.

3. Whereas many games have three core classes (warrior, rogue, wizard) Otrera has four:
Fighter, Mage, Craftsman, Archer. Users can make their own classes and a wider variety
of hybrid and prestige classes with this system.

4. Like Dark Souls, weapons scale with character attributes. Bows do more damage based on DEX
while hammers do more damage based on MGT (Might). 

5. The bulk of a weapon's damage is determined by the scaling of its weapon type. Weapons vary
mainly in terms of their weight, base power, and special attributes. This means that all
weapons are viable to some degree, which allows for greater customization.

6. In combat, evade is distinct from physical defense. Unlike D&D's armor class system,
Otrera differentiates properly between being nimble and hard to hit, or slow and tanky. The
naked and fast build can be just as viable in a melee battle as a guy covered in iron armor.

7. Skills can be locked by class, attribute, level, or some combination. There are both active
and passive skills.

8. Magic is a subset of skills. You don't have to have magic at all actually.

== What about non-combat stuff, like exploring?

Still need to draft this section
